version: '3'
services:

 traefik:
  build:
      context: ./traefik
      dockerfile: dockerfile
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  container_name: traefik_test
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    net:
       ipv4_address: 172.20.0.4
  tty: true
 machine:
  image: katacoda/docker-http-server
  networks:
    net:
       ipv4_address: 172.20.0.5
  labels:
    - "traefik.backend=machine-echo"
    - "traefik.frontend.rule= Host:machine-echo.example.com"
  container_name: http1
 echo:
  image: katacoda/docker-http-server:v2
  networks:
    net:
       ipv4_address: 172.20.0.6
  labels:
    - "traefik.backend=echo"
    - "traefik.frontend.rule= Host:echo-echo.example.com"
  container_name: http2
 client:
   build:
       context: ./client
       dockerfile: docker
   networks:
     net:
       ipv4_address: 172.20.0.2
   container_name: traefik_client
   tty: true
networks:
    net:
       driver: bridge
       ipam:
          driver: default
          config:
           - subnet: 172.20.0.0/16

