version: '3'
services:

 traefik:
  image: ishu06/traefik_test1:trial
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
  networks:
    net:
       ipv4_address: 172.20.0.4
  tty: true
 machine:
  image: katacoda/docker-http-server
  networks:
    net:
       ipv4_address: 172.20.0.5
  labels:
    - "traefik.backend=machine-echo"
    - "traefik.frontend.rule= Host:machine-echo.example.com"
  container_name: http1
 echo:
  image: katacoda/docker-http-server:v2
  networks:
    net:
       ipv4_address: 172.20.0.6
  labels:
    - "traefik.backend=echo"
    - "traefik.frontend.rule= Host:echo-echo.example.com"
  container_name: http2
networks:
    net:
       driver: bridge
       ipam:
          driver: default
          config:
           - subnet: 172.20.0.0/16
