FROM ubuntu:latest
WORKDIR /
RUN apt-get -y update && \\
    apt-get install -y wget && \
    wget https://github.com/containous/traefik/releases/download/v1.7.14/traefik_linux-amd64 && \
    chmod u+x traefik_linux-amd64

COPY entrypoint.sh /

EXPOSE 80 8080 443

ENTRYPOINT ["/entrypoint.sh"]
RUN chmod +x entrypoint.sh
CMD ["/bin/bash"]

